name: brugada-ecg
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip>=20
  - pandas
  - matplotlib
  - jupyterlab
  - ipywidgets
  - xmltodict
  - tqdm
  - pip:
     - keras>=2.6
